function hkl = get_allpermute_triplets(h,k,l)
%hkl = zeros(48, 3);
hkl = [h, k, l];
hkl = [hkl;circshift(hkl,1);circshift(hkl,-1)];
hkl = [hkl;hkl(:,[2,1,3])];
hkl = [hkl;-hkl(:,1), hkl(:,2), hkl(:,3);...
    hkl(:,1), -hkl(:,2), hkl(:,3);...
    hkl(:,1), hkl(:,2), -hkl(:,3);...
    -hkl(:,1), hkl(:,2), -hkl(:,3);...
    hkl(:,1), -hkl(:,2), -hkl(:,3);...
    -hkl(:,1), -hkl(:,2), hkl(:,3);...
    -hkl(:,1), -hkl(:,2), -hkl(:,3);...
    ];
if ~(h~=k && h~=l && k~=l) 
    hkl = unique_m(hkl);
end